homeassistant:
  # Name of the location where Home Assistant is running
  name: LopHocVui
  # Location required to calculate the time the sun rises and sets
  latitude: 20.980842
  longitude: 105.787385
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend: !include frontend.yaml
 
# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   api_password: 123456
   # ssl_certificate: /home/homeassistant/dehydrated/certs/lophocvui.duckdns.org/fullchain.pem
   # ssl_key: /home/homeassistant/dehydrated/certs/lophocvui.duckdns.org/privkey.pem
   # base_url: lophocvui.duckdns.org
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - switch
  exclude:
    entities:
     - switch.fan_1
history_graph: !include history_graph.yaml
# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

#Zone
zone: !include zone.yaml

# Track the sun
sun:

# Weather prediction
# Text to speech
tts:
# Cloud
cloud: !include cloud.yaml

mqtt:
  broker: 127.0.0.1
  port: 1808
  username: HA
  password: 123456
# Sensor
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
switch: !include_dir_merge_list switchs/
light: !include_dir_merge_list lights/
cover: !include_dir_merge_list cover/
# Weather
weather:
  - platform: yweather

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
#device_tracker:
#  - platform: google_maps
#    username: !secret google_maps_username
#    password: !secret google_maps_password
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

panel_iframe:
  cloud9:
    title: 'Cloud9'
    url:  'http://hassbian.local:8181'
    icon: mdi:cloud-tags
  web_terminal:
    title: 'Web terminal'
    icon: mdi:console
    url: 'http://hassbian.local:4200/'

camera:
#  - platform: ffmpeg
#    input: /dev/video0
#    extra_arguments: -pred 1
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/www/dlib/nam.jpg

ifttt:
  key: mdiCKdAnV_DbhPXBckd1ys0h1nGWTc-YPwdvzG8iSfK 

media_player:
  - platform: alexa
    email: "khanh1997777@gmail.com"
    password: "Huyenkhanh"
    url: "amazon.com"
