title: Nhà trẻ mẫu giáo
resources:
  - url: /local/custom_ui/plan-coordinates.js
    type: js
  - url: /local/custom_ui/gauge-card.js
    type: js

# Copy resources from anywhere to www/lovelace and include them
views:
  - title: Lights
    id: lights
    icon: mdi:home-assistant
    panel: true
    cards:
      - type: vertical-stack
        cards: 
          - type: custom:plan-coordinates                    
          - type: picture-elements
            image: /local/home.png
            elements:
              - type: state-icon
                entity: switch.lamp
                tap_action: toggle
                style:
                  top: 95%
                  left: 24%
              - type: state-icon
                entity: switch.fan_bedroom
                tap_action: toggle
                style:
                  top: 56%
                  left: 19%
              - type: state-icon
                entity: switch.fan_kitchen
                tap_action: toggle
                style:
                  top: 7%
                  left: 55%
              - type: state-label
                entity: sensor.date
                style:
                  top: 6%
                  left: 75%
                  color: dark
                  font-size: 30px
                  font-family: Arial
                  text-align: center
                  opacity: 0.8
              - type: state-label
                entity: sensor.time
                style:
                  top: 12%
                  left: 75%
                  color: dark
                  font-size: 30px
                  font-family: Arial
                  text-align: center
                  opacity: 0.8
              - type: state-icon
                entity: switch.light_bathroom
                tap_action: toggle
                style:
                  top: 54%
                  left: 44%
              - type: state-icon
                entity: switch.light_bedroom
                tap_action: toggle
                style:
                  top: 73%
                  left: 31%
              - type: state-icon
                entity: switch.light_garage
                tap_action: toggle
                style:
                  top: 84%
                  left: 44%
              - type: state-icon
                entity: switch.light_kitchen
                tap_action: toggle
                style:
                  top: 28%
                  left: 63%
              - type: state-icon
                entity: switch.light_livingroom
                tap_action: toggle
                style:
                  top: 51%
                  left: 20%
              - type: state-badge
                entity: switch.light_livingroom
                style:
                  top: 71%
                  left: 20%
              - type: image
                entity: group.door1
                tap_action: more-info
                image: /local/images/doors/garage.jpg
                style:
                  top: 84%
                  left: 64%
                  width: 50px
                  height: 50px
                  background: blue
                  -moz-border-radius: 25px
                  -webkit-border-radius: 25px
                  border-radius: 25px
                  border: none
              - type: image
                entity: group.door2
                tap_action: more-info
                image: /local/images/doors/living.jpg
                style:
                  top: 28%
                  left: 3%
                  width: 50px
                  height: 50px
                  background: red
                  -moz-border-radius: 25px
                  -webkit-border-radius: 25px
                  border-radius: 25px
                  border: none
              - type: image
                entity: group.window
                tap_action: more-info
                image: /local/images/doors/window.jpg
                style: 
                  top: 78%
                  left: 3%
                  width: 50px
                  height: 50px
                  background: yellow
                  -moz-border-radius: 25px
                  -webkit-border-radius: 25px
                  border-radius: 25px
                  border: none  
  - title: Sensors
    icon: mdi:weather-partlycloudy
    id: sensors
    cards:
      - type: weather-forecast
        entity: weather.yweather       
      - type: glance
        title: Thời tiết hôm nay 
        entities:
          - entity: sensor.weather_symbol
            name: Dự Báo
          - entity: sensor.weather_temperature
            name: Nhiệt độ
          - entity: sensor.weather_humidity
            name: Độ ẩm
          - entity: sensor.weather_wind_speed
            name: Tốc độ gió
          - entity: sensor.weather_cloudiness
            name: Mây
          - entity: sensor.weather_precipitation
            name: Lượng mưa
  - title: Doors
    id: doors
    icon: mdi:home
    cards:
      - type: entities
        title: Garage door
        entities:
          - cover.garage_door
          - binary_sensor.garage_door
      - type: picture-glance
        title: Cửa Gara
        entities: 
          - switch.garage_door
        state_image:
          "on": /local/images/doors/garage_on.jpg
          "off": /local/images/doors/garage_off.jpg
        entity: switch.garage_door
  - title: Systemd
    id: systemd
    icon: mdi:desktop-classic
    cards:
      - type: entities
        title: System Monitor
        entities:
          - sensor.cpu_speed
          - sensor.memory_free
          - sensor.memory_use_percent
      - type: gauge
        title: Memory Usuage
        unit_of_measurement: '%'
        entity: sensor.memory_use_percent
      - type: entities
        title: Network
        entities:
          - sensor.ipv4_address_wlan0
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
  - title: Setting
    id: settings
    icon: mdi:home
    cards:
      - type: markdown
        content: >
          `Hello`
           \ Tables        \ Are           \ Cool  \
      - type: horizontal-stack
        cards:
          - type: custom:gauge-card
            title: Temperature
            entity: sensor.weather_temperature
            min: -20
            max: 35
          - type: custom:gauge-card
            title: Humidity
            entity: sensor.weather_humidity
            severity:
            red: 50
            green: 0
            amber: 40
   
