title: Nhà trẻ mẫu giáo

# Copy resources from anywhere to www/lovelace and include them
views:
  - title: Lights
    id: lights
    icon: mdi:home-assistant
    cards:
      - type: markdown
        content: >
          ## Welcome Home

          Số nhà 123 
          Phố Nguyễn Văn Trỗi
          Quận Hà Đông 
          Thành phố Hà Nội
      - type: picture-elements
        image: /local/myhome.png
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.the_bedroom_light
            style:
              bottom: 17%
              left: 46%
          - type: state-icon
            tap_action: toggle
            entity: light.the_livingroom_light
            style:
              bottom: 38%
              left: 35%
          - type: state-icon
            tap_action: toggle
            entity: light.the_kitchen_light
            style:
              top: 56%
              left: 62%
          - type: state-label
            entity: sensor.weather_temperature
            prefix: Temperature =     
            style:
              top: 3%
              left: 80%
              color: red
          - type: state-label
            entity: sensor.weather_humidity
            prefix: Humidity =
            style:
              top: 6%
              left: 80%
              color: red

      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.the_kitchen_light
          - light.the_bedroom_light
          - light.the_livingroom_light
      - type: picture-glance
        title: Living room
        image: /local/images/the_livingroom.jpg
        entities:
          - sensor.weather_temperature
          - input_select.pc
          - light.the_livingroom_light
  - title: Sensors
    icon: mdi:weather-partlycloudy
    id: sensors
    cards:
      - type: weather-forecast
        entity: weather.yweather       
      - type: glance
        title: Thời tiết hôm nay 
        entities:
          - entity: sensor.weather_symbol
            name: Dự Báo
          - entity: sensor.weather_temperature
            name: Nhiệt độ
          - entity: sensor.weather_humidity
            name: Độ ẩm
          - entity: sensor.weather_wind_speed
            name: Tốc độ gió
          - entity: sensor.weather_cloudiness
            name: Mây
          - entity: sensor.weather_precipitation
            name: Lượng mưa
  - title: Doors
    id: doors
    icon: mdi:home
    cards:
      - type: entities
        title: Garage door
        entities:
          - cover.garage_door
          - binary_sensor.garage_door
      - type: picture-glance
        title: Cửa Gara
        entities: 
          - switch.garage_door
        state_image:
          "on": /local/images/doors/garage_on.jpg
          "off": /local/images/doors/garage_off.jpg
        entity: switch.garage_door
  - title: Setting
    id: settings
    icon: mdi:desktop-classic
    cards:
      - type: entities
        title: System Monitor
        entities:
          - sensor.cpu_speed
          - sensor.memory_free
          - sensor.memory_use_percent
      - type: gauge
        title: Memory Usuage
        unit_of_measurement: '%'
        entity: sensor.memory_use_percent
      - type: entities
        title: Network
        entities:
          - sensor.ipv4_address_wlan0
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
 
