title: Nhà trẻ mẫu giáo

# Copy resources from anywhere to www/lovelace and include them
views:
  - title: Lights
    id: lights
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.the_kitchen_light
          - light.the_bedroom_light
          - light.the_livingroom_light
      - type: picture-glance
        title: Living room
        image: /local/images/the_livingroom.jpg
        entities:
          - sensor.weather_temperature
          - input_select.pc
          - light.the_livingroom_light
  - title: Sensors
    icon: mdi:cloud-search
    id: sensors
    cards:      
      - type: map
        entities:
          - entity: device_tracker.google_maps_namunjted1234gmailcom
  - title: Setting
    id: settings
    icon: mdi:desktop-classic
    cards:
      - type: entities
        title: System Monitor
        entities:
          - sensor.cpu_speed
          - sensor.memory_free
          - sensor.memory_use_percent
      - type: entities
        title: Network
        entities:
          - sensor.ipv4_address_wlan0
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
